services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"

  app:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env