server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: microservices
    static_configs:
      - targets:
          - localhost
        labels:
          job: microservices
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
      - json:
          source: attrs
          expressions:
            tag: tag
      # Filter out loki, grafana, prometheus, and other non-microservice containers
      - match:
          selector: '{job="microservices"}'
          stages:
            - regex:
                source: tag
                expression: '.*(?P<container_name>loki|grafana|prometheus|redis|rabbitmq|db|migrate).*'
            - drop:
                source: container_name
                expression: '.+'
      # Extract service name from microservices containers
      - match:
          selector: '{job="microservices"}'
          stages:
            - regex:
                source: tag
                expression: '.*microservices-(?P<service>subscription|weather|email|gateway)-.*'
            - labels:
                service:
      - output:
          source: output
