name: Architecture Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  arch-test:
    name: Check architecture boundaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run arch tests
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          gotestsum -- ./test/arch_test