//go

name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    name: Run E2E tests with Rod
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: weatherdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install system dependencies for Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 libxss1 libasound2 libatk1.0-0 libatk-bridge2.0-0 \
            libcups2 libdrm2 libgbm1 libgtk-3-0 libxcomposite1 libxdamage1 \
            libxrandr2 libxshmfence1 wget unzip

      - name: Build & start docker-compose
        run: docker compose up -d --build

      - name: Wait for app to be ready
        run: sleep 5

      - name: Run E2E tests
        run: go test ./test/e2e -v

      - name: Stop containers
        if: always()
        run: docker compose down -v