name: Lint Microservices

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Lint subscription
        working-directory: microservices/subscription
        run: golangci-lint run --timeout=5m

      - name: Lint email
        working-directory: microservices/email
        run: golangci-lint run --timeout=5m

      - name: Lint weather
        working-directory: microservices/weather
        run: golangci-lint run --timeout=5m