name: Lint Microservices

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Download golangci-lint v2.0.0
        run: |
          curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v2.0.0/golangci-lint-2.0.0-linux-amd64.tar.gz | tar -xz
          sudo mv golangci-lint-2.0.0-linux-amd64/golangci-lint /usr/local/bin/

      - name: Lint subscription
        working-directory: microservices/subscription
        run: golangci-lint run --timeout=5m

      - name: Lint email
        working-directory: microservices/email
        run: golangci-lint run --timeout=5m

      - name: Lint weather
        working-directory: microservices/weather
        run: golangci-lint run --timeout=5m