name: Unit and Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run unit tests
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          gotestsum -- ./...

  integration-test:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run integration tests
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          gotestsum -- -tags=integration ./internal/integration/...